language: python

python:
  - "2.6"
  - "2.7"

install:
  - python setup.py install
  - pip install -r requirements-dev.txt

script:
  - cd tests
  - python run_tests.py
  - pep8 run_tests.py
  - cd ../geolinks
  - pep8 links.py
